name: Release Tasks
on:
  release:
    types: [published]
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: |
        VERSION=`echo ${{ github.event.release.tag_name }} | cut -d. -f1`
        git tag -f "${VERSION}"
        git push -f --tags
